### ISSUE TITLE
Dynamic VLAN assignment not working  ?

### ISSUE THREAD

**Issue by lapterchow** [lede-project/source#250] opened 2016-08-10 13:02 UTC
the Chaos Calmer 15.05.1 kernel version 3.18.19 is working fine , 
but LEDE kernel 4.4.15 not working .

**Comment by mkresin** [comment] 2016-08-10 13:37
I'm sorry to say, but your bug report is an example how a bug report should __not__ look like.

I mean you even missed to provide essential informations like tested device. Furthermore, I can only guess what you mean with "Dynamic VLAN assignment".

Please provide at least the following informations:

- Metadata
  - Platform/Device
  - used revision/used release
  - self compiled or [snapshot](http://downloads.lede-project.org/snapshots/)
- Steps to reproduce
- Expected behaviour
- Actual behaviour

**Comment by ttcchl01** [comment] 2016-08-11 02:40
I am Using LEDE snapshot for linksys EA8500  
cat /etc/*_release
DISTRIB_ID='LEDE'
DISTRIB_RELEASE='HEAD'
DISTRIB_REVISION='r1279'
DISTRIB_CODENAME='reboot'
DISTRIB_TARGET='ipq806x/generic'
DISTRIB_DESCRIPTION='LEDE Reboot r1279'
DISTRIB_TAINTS='no-all'

brctl show
bridge name     bridge id               STP enabled     interfaces
breth0.13               8000.00063b014100       no              eth0.13
breth0.14               8000.00063b014100       no              eth0.14
breth0.15               8000.00063b014100       no              eth0.15
breth0.16               8000.00063b014100       no              eth0.16
breth0.17               8000.00063b014100       no              eth0.17
breth0.18               8000.00063b014100       no              eth0.18
breth0.22               8000.00063b014100       no              eth0.22
breth0.23               8000.00063b014100       no              eth0.23
br-br_vlan_12           7fff.00063b014100       yes             eth0.12
                                                        wlan0-3
br-br_vlan_8            7fff.00063b014100       yes             eth0.8
                                                        wlan1
                                                        wlan0
                                                        wlan0-1
                                                        wlan1-1
br-lan          7fff.00063b014100       yes             eth0.88

wireless client unable connect to the router
log of radius server
Auth: Login OK: [usertest] (from client 10.126.88.2 port 1 cli xx-xx-xx-xx-xx-xx via TLS tunnel)
Thu Aug 11 10:03:57 2016 : Auth: rlm_perl: Returning vlan 13 to request from xx-xx-xx-xx-xx-xx port 1




------------- working router status 
this is working status brctl show
brctl show
bridge name     bridge id               STP enabled     interfaces
breth0.13               8000.02f0210f953f       no              eth0.13
                                                        wlan0.13
breth0.14               8000.04f021041419       no              eth0.14

there missing                        wlan0.13   bridge 
may be /sbin/netifd or /lib/netifd/hostapd.sh   script not support kenel 4.X ?

**Comment by kbabioch** [comment] 2016-08-29 18:12
Your report is still missing essential information. What is the expected behavior? What is actually happening instead? Posting a bunch of log files is no good, if one does not know what to look for. What software (stack) are you using? where should wlan0.13 come from? What is dynamic about your setup? Looks like static VLAN assignments to me?

**Comment by thess** [comment] 2016-09-04 16:37
@lapterchow 

This is not a very good bug report and I am not moving it to our issue tracking system. I am closing this here and invite you to re-file your issue and some supporting information at https://bugs.lede-project.org.

**Closed by thess** 2016-09-04 16:37 UTC
