### ISSUE TITLE
cns3xxx: ath9k crash caught on boot

### ISSUE THREAD

**Issue by xback** [lede-project/source#168] opened 2016-07-01 09:03 UTC
Revision: f576ff05a1523a0c61a3399087454034d4739f2c
Hardware used: Gateworks Laguna GW2388
WiFi HW: 4x UBNT SR71-15

Bug: Crash on boot / Kernel Oops (NULL deref.)
Repro rate: Very low

[   35.040000] wlan0: Trigger new scan to find an IBSS to join
[   37.040000] wlan3: Trigger new scan to find an IBSS to join
[   37.050000] wlan1: Trigger new scan to find an IBSS to join
[   37.050000] wlan2: Trigger new scan to find an IBSS to join
[   37.710000] random: nonblocking pool is initialized
[   39.040000] wlan0: Trigger new scan to find an IBSS to join
[   40.440000] wlan0: Creating new IBSS network, BSSID f8:79:77:57:aa:7d
[   41.040000] wlan3: Trigger new scan to find an IBSS to join
[   41.050000] wlan1: Trigger new scan to find an IBSS to join
[   41.050000] wlan2: Trigger new scan to find an IBSS to join
[   42.500000] wlan1: Selected IBSS BSSID f8:79:77:57:aa:7d based on configured SSID
[   42.530000] wlan2: Selected IBSS BSSID f8:79:77:57:aa:7d based on configured SSID
[   42.550000] wlan3: Selected IBSS BSSID f8:79:77:57:aa:7d based on configured SSID
[   42.560000] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[   42.560000] pgd = c0004000
[   42.560000] [00000000] *pgd=00000000
[   42.560000] Internal error: Oops: 80000007 [#1] SMP ARM
[   42.560000] Modules linked in: dummy ath9k ath9k_common qcserial pppoe ppp_async option iptable_nat ath9k_hw ath usb_wwan sierra pppox ppp_generic nf_nat_ipv4 nf_conntrack_netlink nf_conntrack_ipv6 nf]
[   42.560000] CPU: 0 PID: 14 Comm: kworker/u4:1 Not tainted 4.4.14 #2
[   42.560000] Hardware name: Gateworks Corporation Laguna Platform
[   42.560000] Workqueue: phy2 ieee80211_iface_work [mac80211]
[   42.560000] task: cf837640 ti: cf894000 task.ti: cf894000
[   42.560000] PC is at 0x0
[   42.560000] LR is at handle_edge_irq+0x98/0x1b4
[   42.560000] pc : [<00000000>]    lr : [<c00652f0>]    psr: 60000193
[   42.560000] sp : cf895938  ip : cf895938  fp : cf89594c
[   42.560000] r10: fb005100  r9 : cf808190  r8 : c04f0524
[   42.560000] r7 : c04fbff4  r6 : 04000000  r5 : cfa5e250  r4 : cfa5e240
[   42.560000] r3 : 00000000  r2 : cfa21950  r1 : 00000000  r0 : cfa5e250
[   42.560000] Flags: nZCv  IRQs off  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
[   42.560000] Control: 00c5787d  Table: 2de1400a  DAC: 00000055
[   42.560000] Process kworker/u4:1 (pid: 14, stack limit = 0xcf894190)
[   42.560000] Stack: (0xcf895938 to 0xcf896000)
[   42.560000] 5920:                                                       0000001a 00000001
[   42.560000] 5940: cf89595c cf895950 c006155c c0065264 cf895984 cf895960 c00249b0 c0061540
[   42.560000] 5960: c04dcf4c 0000002c 00000000 00000001 cf802000 00000000 cf895994 cf895988
[   42.560000] 5980: c006155c c0024938 cf8959bc cf895998 c006185c c0061540 fb00410c cf8959f0
[   42.560000] 59a0: c04f05a0 fb004100 c04e4534 00000000 cf8959ec cf8959c0 c00093d4 c00617dc
[   42.560000] 59c0: bf47aa90 c00134e4 60000013 ffffffff cf895a24 60000013 cdc11ea8 40000013
[   42.560000] 59e0: cf895a4c cf8959f0 c000a380 c0009384 cdc11ea4 60000013 00000000 00005605
[   42.560000] 5a00: d4e8402c cdc114e0 00023f60 cdc11ea4 60000013 cdc11ea8 40000013 cf895a4c
[   42.560000] 5a20: cf895a50 cf895a40 bf47aa90 c00134e4 60000013 ffffffff c0020464 c00233b8
[   42.560000] 5a40: cf895a74 cf895a50 bf47aa90 c00134c4 ce39a010 ce39a038 00023f60 00000002
[   42.560000] 5a60: bf47aa34 cdc11ea8 cf895aa4 cf895a78 bf40e5d0 bf47aa40 cf895aa4 cdc114e0
[   42.560000] 5a80: 00000001 cdc114e0 00000001 ce39a010 cdc11ea0 ce39a038 cf895ad4 cf895aa8
[   42.560000] 5aa0: bf47d83c bf40e478 bf47d5b4 cdc11e70 cdc11e74 c04dc154 00000000 cf895ad8
[   42.560000] 5ac0: c04fc520 cf894000 cf895b0c cf895ad8 c002ac94 bf47d5c0 cf895b0c 00000000
[   42.560000] 5ae0: c0294168 00000000 00000006 c04e4058 c04e404c 40000003 00000101 cf894000
[   42.560000] 5b00: cf895b54 cf895b10 c002ae18 c002ac00 00000000 00000000 04208060 ffff9b70
[   42.560000] 5b20: 0000000a cf895b10 bf3822ec 20000013 ce1f1e78 ce1f1e8c 00000000 00000000
[   42.560000] 5b40: ce0ec010 ce0ec408 cf895b6c cf895b58 c002affc c002ad74 00000200 ce1f1e78
[   42.560000] 5b60: cf895b84 cf895b70 c002b098 c002afd0 ce1f14e0 ce1f1e78 cf895b94 cf895b88
[   42.560000] 5b80: c00139c4 c002b014 cf895bdc cf895b98 bf47e088 c001399c bf47a8e4 c00134c4
[   42.560000] 5ba0: ce0ec038 ce1f1eac ce1f300c ce1f293c cf895bdc ce1f14e0 ce0ec010 ce0ec408
[   42.560000] 5bc0: ce0ec010 ce1f28e8 ce0ec0dc ce1f0b60 cf895bfc cf895be0 bf47e120 bf47decc
[   42.560000] 5be0: ce1f14e0 ce1f24e0 000003f8 ce0ec010 cf895c44 cf895c00 bf486f50 bf47e0ec
[   42.560000] 5c00: ce1f1ea8 20000013 ce0ec010 ce0ec038 ce1f9c20 0000000e cf895c44 ce1f14e0
[   42.560000] 5c20: ce1f0b60 00000042 ce1f1eb0 ce1f28e8 ce0ec010 00000001 cf895c7c cf895c48
[   42.560000] 5c40: bf47d044 bf486d84 cf895c80 cf895c68 bf386eac ce1f0b60 00000040 0000001e
[   42.560000] 5c60: ce1f9c20 00000000 cf895d70 00000001 cf895cc4 cf895c80 bf358658 bf47ce30
[   42.560000] 5c80: 00000001 ce1f0b60 cf895cb4 cf895c98 ce1f9c20 00000002 0000167b 00000000
[   42.560000] 5ca0: cfbaede0 ce1f0b60 00000000 cfbaee10 ce1f0b60 ce1f129c cf895ce4 cf895cc8
[   42.560000] 5cc0: bf386b04 bf3583f8 cfbaede0 ce1f0b60 00000000 ce1f0b60 cf895d04 cf895ce8
[   42.560000] 5ce0: bf38712c bf386ab0 ce1f1290 ce398440 00000000 ce1f0b60 cf895d34 cf895d08
[   42.560000] 5d00: bf388da0 bf387110 cf837640 ce398440 cf895d70 ce1f0b60 ce70b114 cf895df8
[   42.560000] 5d20: 00000000 ce70b12d cf895dc4 cf895d38 bf36731c bf388b90 00000000 00000001
[   42.560000] 5d40: c051f784 00000000 c051f778 c051f788 60000013 00000000 00000012 ce1f11b4
[   42.560000] 5d60: 00000064 ce1f9c20 00000003 c04ec640 ce1f9c20 00000002 0000167b 00000000
[   42.560000] 5d80: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 ce70b11c
[   42.560000] 5da0: ce398440 00000007 00000064 ce0ec178 00000015 ce70b12d cf895e34 cf895dc8
[   42.560000] 5dc0: bf39b9bc bf367120 00000015 00000012 001c2149 00000000 00000000 00000200
[   42.560000] 5de0: ce70b11c ce70b12d 00000008 0000006c 00000000 00000005 ce1f9c20 00000002
[   42.560000] 5e00: 0000167b 00000000 c005de6c ce70b11c ce398440 ce1f0b60 ce39894a 00000200
[   42.560000] 5e20: 00000100 ce39846c cf895e9c cf895e38 bf368af4 bf39b784 00000010 00000002
[   42.560000] 5e40: 00000000 c00c69e4 00000001 ce398910 ce096780 cdc626c0 ce398844 ce398854
[   42.560000] 5e60: ce1f0b60 ce398440 cf895e84 cf895e78 cf895e9c 00000000 cdc626c0 ce398844
[   42.560000] 5e80: ce398854 ce1f0b60 ce398440 00000000 cf895eec cf895ea0 bf36a380 bf3689b4
[   42.560000] 5ea0: ce09a470 00000001 cf895ec4 cf895eb8 bf381898 c0039560 ce628600 00000000
[   42.560000] 5ec0: cf895eec ce398844 cf882000 cf802800 00000000 ce628d00 00000000 00000000
[   42.560000] 5ee0: cf895f24 cf895ef0 c003b510 bf36a03c 00000088 cf802814 cf802800 cf882000
[   42.560000] 5f00: cf882018 cf802800 00000088 cf802814 cf802800 00000000 cf895f5c cf895f28
[   42.560000] 5f20: c003b9c4 c003b2f0 c003b6a8 cf802964 00000000 00000000 cf883000 cf882000
[   42.560000] 5f40: c003b6a8 00000000 00000000 00000000 cf895fac cf895f60 c00408b8 c003b6b4
[   42.560000] 5f60: 00000000 00000000 00000000 cf882000 00000000 00000000 cf895f78 cf895f78
[   42.560000] 5f80: 00000000 00000000 cf895f88 cf895f88 cf883000 c00407d0 00000000 00000000
[   42.560000] 5fa0: 00000000 cf895fb0 c0009ae8 c00407dc 00000000 00000000 00000000 00000000
[   42.560000] 5fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[   42.560000] 5fe0: 00000000 00000000 00000000 00000000 00000013 00000000 7c9d3575 7d574555
[   42.560000] Backtrace: 
[   42.560000] [<c0065258>] (handle_edge_irq) from [<c006155c>] (generic_handle_irq+0x28/0x3c)
[   42.560000]  r5:00000001 r4:0000001a
[   42.560000] [<c0061534>] (generic_handle_irq) from [<c00249b0>] (cns3xxx_gpio_irq_handler+0x84/0xa8)
[   42.560000] [<c002492c>] (cns3xxx_gpio_irq_handler) from [<c006155c>] (generic_handle_irq+0x28/0x3c)
[   42.560000]  r9:00000000 r8:cf802000 r7:00000001 r6:00000000 r5:0000002c r4:c04dcf4c
[   42.560000] [<c0061534>] (generic_handle_irq) from [<c006185c>] (__handle_domain_irq+0x8c/0xb8)
[   42.560000] [<c00617d0>] (__handle_domain_irq) from [<c00093d4>] (gic_handle_irq+0x5c/0xa4)
[   42.560000]  r9:00000000 r8:c04e4534 r7:fb004100 r6:c04f05a0 r5:cf8959f0 r4:fb00410c
[   42.560000] [<c0009378>] (gic_handle_irq) from [<c000a380>] (__irq_svc+0x40/0x54)
[   42.560000] Exception stack(0xcf8959f0 to 0xcf895a38)
[   42.560000] 59e0:                                     cdc11ea4 60000013 00000000 00005605
[   42.560000] 5a00: d4e8402c cdc114e0 00023f60 cdc11ea4 60000013 cdc11ea8 40000013 cf895a4c
[   42.560000] 5a20: cf895a50 cf895a40 bf47aa90 c00134e4 60000013 ffffffff
[   42.560000]  r10:40000013 r9:cdc11ea8 r8:60000013 r7:cf895a24 r6:ffffffff r5:60000013
[   42.560000]  r4:c00134e4 r3:bf47aa90
[   42.560000] [<c00134b8>] (_raw_spin_unlock_irqrestore) from [<bf47aa90>] (ath9k_iowrite32+0x5c/0x7c [ath9k])
[   42.560000] [<bf47aa34>] (ath9k_iowrite32 [ath9k]) from [<bf40e5d0>] (ath9k_hw_enable_interrupts+0x164/0x210 [ath9k_hw])
[   42.560000]  r9:cdc11ea8 r8:bf47aa34 r7:00000002 r6:00023f60 r5:ce39a038 r4:ce39a010
[   42.560000] [<bf40e46c>] (ath9k_hw_enable_interrupts [ath9k_hw]) from [<bf47d83c>] (ath9k_tasklet+0x288/0x2f0 [ath9k])
[   42.560000]  r8:ce39a038 r7:cdc11ea0 r6:ce39a010 r5:00000001 r4:cdc114e0
[   42.560000] [<bf47d5b4>] (ath9k_tasklet [ath9k]) from [<c002ac94>] (tasklet_action+0xa0/0x118)
[   42.560000]  r10:cf894000 r9:c04fc520 r8:cf895ad8 r7:00000000 r6:c04dc154 r5:cdc11e74
[   42.560000]  r4:cdc11e70 r3:bf47d5b4
[   42.560000] [<c002abf4>] (tasklet_action) from [<c002ae18>] (__do_softirq+0xb0/0x204)
[   42.560000]  r10:cf894000 r9:00000101 r8:40000003 r7:c04e404c r6:c04e4058 r5:00000006
[   42.560000]  r4:00000000
[   42.560000] [<c002ad68>] (__do_softirq) from [<c002affc>] (do_softirq.part.2+0x38/0x44)
[   42.560000]  r10:ce0ec408 r9:ce0ec010 r8:00000000 r7:00000000 r6:ce1f1e8c r5:ce1f1e78
[   42.560000]  r4:20000013
[   42.560000] [<c002afc4>] (do_softirq.part.2) from [<c002b098>] (__local_bh_enable_ip+0x90/0xd0)
[   42.560000]  r5:ce1f1e78 r4:00000200
[   42.560000] [<c002b008>] (__local_bh_enable_ip) from [<c00139c4>] (_raw_spin_unlock_bh+0x34/0x38)
[   42.560000]  r5:ce1f1e78 r4:ce1f14e0
[   42.560000] [<c0013990>] (_raw_spin_unlock_bh) from [<bf47e088>] (ath9k_calculate_summary_state+0x654/0x6ac [ath9k])
[   42.560000] [<bf47dec0>] (ath9k_calculate_summary_state [ath9k]) from [<bf47e120>] (ath_reset+0x40/0x54 [ath9k])
[   42.560000]  r10:ce1f0b60 r9:ce0ec0dc r8:ce1f28e8 r7:ce0ec010 r6:ce0ec408 r5:ce0ec010
[   42.560000]  r4:ce1f14e0
[   42.560000] [<bf47e0e0>] (ath_reset [ath9k]) from [<bf486f50>] (ath_chanctx_set_channel+0x1d8/0x284 [ath9k])
[   42.560000]  r7:ce0ec010 r6:000003f8 r5:ce1f24e0 r4:ce1f14e0
[   42.560000] [<bf486d78>] (ath_chanctx_set_channel [ath9k]) from [<bf47d044>] (ath9k_config+0x220/0x250 [ath9k])
[   42.560000]  r10:00000001 r9:ce0ec010 r8:ce1f28e8 r7:ce1f1eb0 r6:00000042 r5:ce1f0b60
[   42.560000]  r4:ce1f14e0
[   42.560000] [<bf47ce24>] (ath9k_config [ath9k]) from [<bf358658>] (ieee80211_hw_config+0x26c/0x2a0 [mac80211])
[   42.560000]  r10:00000001 r9:cf895d70 r8:00000000 r7:ce1f9c20 r6:0000001e r5:00000040
[   42.560000]  r4:ce1f0b60
[   42.560000] [<bf3583ec>] (ieee80211_hw_config [mac80211]) from [<bf386b04>] (ieee80211_iter_chan_contexts_atomic+0x564/0x63c [mac80211])
[   42.560000]  r8:ce1f129c r7:ce1f0b60 r6:cfbaee10 r5:00000000 r4:ce1f0b60
[   42.560000] [<bf386aa4>] (ieee80211_iter_chan_contexts_atomic [mac80211]) from [<bf38712c>] (ieee80211_recalc_chanctx_min_def+0x3ec/0x430 [mac80211])
[   42.560000]  r7:ce1f0b60 r6:00000000 r5:ce1f0b60 r4:cfbaede0
[   42.560000] [<bf387104>] (ieee80211_recalc_chanctx_min_def [mac80211]) from [<bf388da0>] (ieee80211_vif_use_channel+0x21c/0x23c [mac80211])
[   42.560000]  r7:ce1f0b60 r6:00000000 r5:ce398440 r4:ce1f1290
[   42.560000] [<bf388b84>] (ieee80211_vif_use_channel [mac80211]) from [<bf36731c>] (__ieee80211_sta_join_ibss+0x208/0x118c [mac80211])
[   42.560000]  r10:ce70b12d r9:00000000 r8:cf895df8 r7:ce70b114 r6:ce1f0b60 r5:cf895d70
[   42.560000]  r4:ce398440 r3:cf837640
[   42.560000] [<bf367114>] (__ieee80211_sta_join_ibss [mac80211]) from [<bf39b9bc>] (ieee80211_sta_join_ibss+0x244/0x250 [mac80211])
[   42.560000]  r10:ce70b12d r9:00000015 r8:ce0ec178 r7:00000064 r6:00000007 r5:ce398440
[   42.560000]  r4:ce70b11c
[   42.560000] [<bf39b778>] (ieee80211_sta_join_ibss [mac80211]) from [<bf368af4>] (ieee80211_ibss_work+0x14c/0x4a0 [mac80211])
[   42.560000]  r10:ce39846c r9:00000100 r8:00000200 r7:ce39894a r6:ce1f0b60 r5:ce398440
[   42.560000]  r4:ce70b11c
[   42.560000] [<bf3689a8>] (ieee80211_ibss_work [mac80211]) from [<bf36a380>] (ieee80211_iface_work+0x350/0x380 [mac80211])
[   42.560000]  r10:00000000 r9:ce398440 r8:ce1f0b60 r7:ce398854 r6:ce398844 r5:cdc626c0
[   42.560000]  r4:00000000
[   42.560000] [<bf36a030>] (ieee80211_iface_work [mac80211]) from [<c003b510>] (process_one_work+0x22c/0x3c4)
[   42.560000]  r10:00000000 r9:00000000 r8:ce628d00 r7:00000000 r6:cf802800 r5:cf882000
[   42.560000]  r4:ce398844
[   42.560000] [<c003b2e4>] (process_one_work) from [<c003b9c4>] (worker_thread+0x31c/0x548)
[   42.560000]  r10:00000000 r9:cf802800 r8:cf802814 r7:00000088 r6:cf802800 r5:cf882018
[   42.560000]  r4:cf882000
[   42.560000] [<c003b6a8>] (worker_thread) from [<c00408b8>] (kthread+0xe8/0xf8)
[   42.560000]  r10:00000000 r9:00000000 r8:00000000 r7:c003b6a8 r6:cf882000 r5:cf883000
[   42.560000]  r4:00000000
[   42.560000] [<c00407d0>] (kthread) from [<c0009ae8>] (ret_from_fork+0x14/0x2c)
[   42.560000]  r7:00000000 r6:00000000 r5:c00407d0 r4:cf883000
[   42.560000] Code: bad PC value
[   42.560000] ---[ end trace 1635424e88052ac4 ]---
[   42.560000] Kernel panic - not syncing: Fatal exception in interrupt
[   42.560000] CPU1: stopping
[   42.560000] CPU: 1 PID: 27 Comm: kworker/u4:2 Tainted: G      D         4.4.14 #2
[   42.560000] Hardware name: Gateworks Corporation Laguna Platform
[   42.560000] Workqueue: phy3 ieee80211_iface_work [mac80211]
[   42.560000] Backtrace: 
[   42.560000] [<c001bf70>] (dump_backtrace) from [<c001c174>] (show_stack+0x18/0x1c)
[   42.560000]  r7:00000000 r6:c04f02e8 r5:60000193 r4:00000000
[   42.560000] [<c001c15c>] (show_stack) from [<c0175244>] (dump_stack+0x98/0xb4)
[   42.560000] [<c01751ac>] (dump_stack) from [<c001e1dc>] (handle_IPI+0xfc/0x1b8)
[   42.560000]  r7:cf925b48 r6:00000000 r5:00000001 r4:c04fbe58
[   42.560000] [<c001e0e0>] (handle_IPI) from [<c0009400>] (gic_handle_irq+0x88/0xa4)
[   42.560000]  r7:fb004100 r6:c04f05a0 r5:cf925b48 r4:fb00410c
[   42.560000] [<c0009378>] (gic_handle_irq) from [<c000a380>] (__irq_svc+0x40/0x54)
[   42.560000] Exception stack(0xcf925b48 to 0xcf925b90)
[   42.560000] 5b40:                   cfa5e2a0 40000013 00000000 00000002 cdc114e0 cdc11e78
[   42.560000] 5b60: ce39a318 ce39a010 cdc128e8 ce39a010 ce39a318 cf925bdc cf925b28 cf925b98
[   42.560000] 5b80: c0061f9c bf47df20 20000013 ffffffff
[   42.560000]  r10:ce39a318 r9:ce39a010 r8:cdc128e8 r7:cf925b7c r6:ffffffff r5:20000013
[   42.560000]  r4:bf47df20 r3:c0061f9c
[   42.560000] [<bf47dec0>] (ath9k_calculate_summary_state [ath9k]) from [<bf47e120>] (ath_reset+0x40/0x54 [ath9k])
[   42.560000]  r10:cdc10b60 r9:ce39a0dc r8:cdc128e8 r7:ce39a010 r6:ce39a318 r5:ce39a010
[   42.560000]  r4:cdc114e0
[   42.560000] [<bf47e0e0>] (ath_reset [ath9k]) from [<bf486f50>] (ath_chanctx_set_channel+0x1d8/0x284 [ath9k])
[   42.560000]  r7:ce39a010 r6:00000308 r5:cdc124e0 r4:cdc114e0
[   42.560000] [<bf486d78>] (ath_chanctx_set_channel [ath9k]) from [<bf47ceac>] (ath9k_config+0x88/0x250 [ath9k])
[   42.560000]  r10:00000001 r9:ce39a010 r8:cdc128e8 r7:cdc11eb0 r6:00000100 r5:cdc10b60
[   42.560000]  r4:cdc114e0
[   42.560000] [<bf47ce24>] (ath9k_config [ath9k]) from [<bf358658>] (ieee80211_hw_config+0x26c/0x2a0 [mac80211])
[   42.560000]  r10:00000001 r9:cf925d70 r8:00000000 r7:ce1fc810 r6:00000017 r5:00000100
[   42.560000]  r4:cdc10b60
[   42.560000] [<bf3583ec>] (ieee80211_hw_config [mac80211]) from [<bf386adc>] (ieee80211_iter_chan_contexts_atomic+0x53c/0x63c [mac80211])
[   42.560000]  r8:cdc1129c r7:cdc10b60 r6:ce0b5540 r5:cdc10b60 r4:cdc10b60
[   42.560000] [<bf386aa4>] (ieee80211_iter_chan_contexts_atomic [mac80211]) from [<bf38712c>] (ieee80211_recalc_chanctx_min_def+0x3ec/0x430 [mac80211])
[   42.560000]  r7:cdc10b60 r6:00000000 r5:cdc10b60 r4:ce0b5540
[   42.560000] [<bf387104>] (ieee80211_recalc_chanctx_min_def [mac80211]) from [<bf388da0>] (ieee80211_vif_use_channel+0x21c/0x23c [mac80211])
[   42.560000]  r7:cdc10b60 r6:00000000 r5:ce39e440 r4:cdc11290
[   42.560000] [<bf388b84>] (ieee80211_vif_use_channel [mac80211]) from [<bf36731c>] (__ieee80211_sta_join_ibss+0x208/0x118c [mac80211])
[   42.560000]  r10:cf2a75ad r9:00000000 r8:cf925df8 r7:cf2a7594 r6:cdc10b60 r5:cf925d70
[   42.560000]  r4:ce39e440 r3:cf89ae80
[   42.560000] [<bf367114>] (__ieee80211_sta_join_ibss [mac80211]) from [<bf39b9bc>] (ieee80211_sta_join_ibss+0x244/0x250 [mac80211])
[   42.560000]  r10:cf2a75ad r9:00000015 r8:ce39a178 r7:00000064 r6:00000007 r5:ce39e440
[   42.560000]  r4:cf2a759c
[   42.560000] [<bf39b778>] (ieee80211_sta_join_ibss [mac80211]) from [<bf368af4>] (ieee80211_ibss_work+0x14c/0x4a0 [mac80211])
[   42.560000]  r10:ce39e46c r9:00000100 r8:00000200 r7:ce39e94a r6:cdc10b60 r5:ce39e440
[   42.560000]  r4:cf2a759c
[   42.560000] [<bf3689a8>] (ieee80211_ibss_work [mac80211]) from [<bf36a380>] (ieee80211_iface_work+0x350/0x380 [mac80211])
[   42.560000]  r10:00000000 r9:ce39e440 r8:cdc10b60 r7:ce39e854 r6:ce39e844 r5:ce298d80
[   42.560000]  r4:00000000
[   42.560000] [<bf36a030>] (ieee80211_iface_work [mac80211]) from [<c003b510>] (process_one_work+0x22c/0x3c4)
[   42.560000]  r10:00000000 r9:00000000 r8:ce3f0400 r7:00000000 r6:cf802800 r5:cf882060
[   42.560000]  r4:ce39e844
[   42.560000] [<c003b2e4>] (process_one_work) from [<c003b9c4>] (worker_thread+0x31c/0x548)
[   42.560000]  r10:00000000 r9:cf802800 r8:cf802814 r7:00000088 r6:cf802800 r5:cf882078
[   42.560000]  r4:cf882060
[   42.560000] [<c003b6a8>] (worker_thread) from [<c00408b8>] (kthread+0xe8/0xf8)
[   42.560000]  r10:00000000 r9:00000000 r8:00000000 r7:c003b6a8 r6:cf882060 r5:cf883000
[   42.560000]  r4:00000000
[   42.560000] [<c00407d0>] (kthread) from [<c0009ae8>] (ret_from_fork+0x14/0x2c)
[   42.560000]  r7:00000000 r6:00000000 r5:c00407d0 r4:cf883000
[   42.560000] Rebooting in 3 seconds..

**Comment by blogic** [comment] 2016-07-02 06:02
duplicate of the bug in flyspray

**Closed by blogic** 2016-07-02 06:02 UTC
